name=MBXRabbitGo
version=2.1.1
author=MBX Robotics
maintainer=MBX Robotics <mbxrobotics@gmail.com>
sentence=MBXRabbitGo Robot Kit Library.
paragraph=Core control library for the MBX RabbitGo robot, providing easy-to-use functions for controlling motors, sensors, and other onboard components.
category=Device Control
url=https://github.com/MBX-Robotics/MBXRabbitGo
architectures=esp32
includes=MBXRabbitGo.h
