name=MBXRabbitGo
version=2.1.4
author=MBX Robotics
maintainer=MBX Robotics <mbxrobotics@gmail.com>
sentence=MBXRabbitGo Robot Kit Library.
paragraph=Core control library for the MBX RabbitGo robot, providing easy-to-use functions for controlling motors, sensors, and onboard components.
category=Device Control
url=https://github.com/MBXRobotics/MBXRabbitGo
architectures=*
includes=MBXRabbitGo.h
depends=ESP32Servo, Adafruit GFX Library, Adafruit ST7735 and ST7789 Library, Adafruit NeoPixel, TFT_eSPI
